models/Post.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use app\models\interface_\InterfaceStatus;

class Post extends ActiveRecord implements InterfaceStatus
{
    public const CHAR_PER_MINUTE = 1200;
    public const COMMENT_ON = 1;
    public const COMMENT_OFF = 2;
    /**
     * @return int
     */
    public function getCountLike() : int
    {
        return Rating::find()->where(['post_id' => $this->id, 'status' => Rating::TYPE_LIKE])->count();
    }

    /**
     * @return int
     */
    public function getCountDislike() : int
    {
        return Rating::find()->where(['post_id' => $this->id, 'status' => Rating::TYPE_DISLIKE])->count();
    }

    /**
     * @return array of Post object
     */
    public function getComments() : array
    {
        return Comment::find()->where(['post_id' => $this->id])->all();
    }

    /**
     * @return Category
     */
    public function getCategory() : Category
    {
        return Category::findOne(['id' => $this->category_id]);
    }

    /**
     * @return User
     */
    public function getUser() : User
    {
        return User::findOne(['id' => $this->user_id]);
    }

    /**
     * @return bool
     */
    public function isLike() : bool
    {
        $rating = $this->getRating();
        if ($rating !== null) {
            return $rating->status == Rating::TYPE_LIKE;
        }

        return false;
    }

    /**
     * @return bool
     */
    public function isDisLike() : bool
    {
        $rating = $this->getRating();
        if ($rating !== null) {
            return $rating->status == Rating::TYPE_DISLIKE;
        }

        return false;
    }

    /**
     * @return bool
     */
    public function isBookmark() : bool
    {
        return !empty(Bookmark::findOne([
            'user_id' => Yii::$app->getUser()->id,
            'post_id' => $this->id
        ]));
    }

    /**
     * @return Rating|null
     */
    protected function getRating() : ?Rating
    {
        $rating = Rating::findOne([
            'user_id' => Yii::$app->getUser()->id,
            'post_id' => $this->id
        ]);

        return $rating;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public static function getRecent()
    {
        return Post::find()->where(['<>', 'status_check', Post::STATUS_BAN]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public static function getPopular()
    {
        return Post::find()->select([
            sprintf('
            * , COALESCE((SELECT COUNT(rating.status)
             FROM rating WHERE rating.status = %s
            AND post.id = rating.post_id)) as count_like', Rating::TYPE_LIKE)
        ])->where(['<>', 'status_check', Post::STATUS_BAN]);
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return self::getStatusAll()[$this->status_check];
    }

    /**
     * @return array
     */
    public static function getStatusAll() : array
    {
        return [
            self::STATUS_NOT_APPROVED => 'Не проверенно',
            self::STATUS_APPROVED => 'Проверенно',
            self::STATUS_BAN => 'Забанен'
        ];
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\form\CommentForm;
use Yii;
use app\models\form\PostForm;
use app\models\Post;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\helpers\FileHelper;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;
use app\models\Comment;

class PostController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex() : string
    {
        $posts = Post::getRecent();
        $pages = new Pagination(['totalCount' => $posts->count(), 'pageSize' => Yii::$app->params['numberOfPage']]);
        $posts = $posts->offset($pages->offset)
            ->limit($pages->limit)->orderBy(['created_at' => SORT_DESC])
            ->all();

        return $this->render('index', ['pages' => $pages, 'posts' => $posts,]);
    }

    /**
     * @param int $id
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView(int $id) : string
    {
        $post = Post::findOne(['id' => $id]);
        if (empty($post)) {
            throw new NotFoundHttpException();
        } elseif ($post->status_check == Post::STATUS_BAN) {
            return $this->render('/error', ['message' => 'post ban admin']);
        }
        $model = new CommentForm();
        $dataProvider = new ActiveDataProvider([
            'query' => Comment::find()->where(['post_id' => $post->id]),
            'pagination' => [
                'pageSize' => Yii::$app->params['numberOfComment'],
            ],
        ]);

        return $this->render('page', ['post' => $post, 'model' => $model, 'dataProvider' => $dataProvider]);
    }

    /**
     * @return string|Response
     * @throws \yii\base\Exception
     */
    public function actionSave()
    {
        if (!Yii::$app->user->isGuest) {
            $model = new PostForm();
            $model->addSetting('image', ['skipOnEmpty' => false]);
            if ($model->load(Yii::$app->request->post())) {
                $model->save();

                $this->redirect(sprintf('/user/%s', Yii::$app->user->getId()));
            }

            return $this->render('create', ['model' => $model]);
        }

        return $this->redirect('/user/login');
    }

    /**
     * @return string
     */
    public function actionRecent() : string
    {
        return $this->actionIndex();
    }

    /**
     * @return string
     */
    public function actionPopular() : string
    {
        $posts = Post::getPopular();
        $pages = new Pagination(['totalCount' => $posts->count(), 'pageSize' => Yii::$app->params['numberOfPage']]);
        $posts = $posts->offset($pages->offset)
            ->limit($pages->limit)->orderBy(['count_like' => SORT_DESC])
            ->all();

        return $this->render('index', ['pages' => $pages, 'posts' => $posts]);
    }

    /**
     * @param int $post_id
     *
     * @return string|Response
     * @throws \Throwable
     * @throws \yii\base\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionEdit(int $post_id)
    {
        $post = Post::findOne($post_id);
        if (!Yii::$app->user->isGuest && $post->user_id === Yii::$app->user->getId()) {
            $model = new PostForm();
            $model->attributes = $post->getAttributes();
            if ($model->load(Yii::$app->request->post())) {
                $model->update($post);
            }

            return $this->render('create', [
                'model' => $model
            ]);
        }

        throw new NotFoundHttpException('post not found or does not belong to this user ');
    }

    /**
     * @param int $post_id
     *
     * @return \yii\web\Response
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionRemove(int $post_id) : Response
    {
        $post = Post::findOne($post_id);
        if (!Yii::$app->user->isGuest && $post->user_id === Yii::$app->user->getId()) {
            FileHelper::unlink(sprintf('image_db/%s', $post->image));
            $post->delete();
        }

        return $this->redirect('/user/' . Yii::$app->user->getId());
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\form\SignupForm;
use app\models\User;
use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\form\LoginForm;

class UserController extends Controller
{
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() : Response
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionSignUp() : string
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->signup() == true) {
                Yii::$app->session->setFlash('success', 'Пользователь успешно зарегистрирован');
            } else {
                Yii::$app->session->setFlash('error', 'Пользователь не зарегистрирван');
            }
        }

        return $this->render('signup', ['model' => $model]);
    }

    /**
     * @param int $id
     *
     * @return string
     */
    public function actionView(int $id) : string
    {
        $user = User::findOne(['id' => $id]);
        if ($user && $user->status != User::STATUS_BAN) {
            $result = User::getPosts($user, Yii::$app->params['numberOfPage']);
            if (count($result['posts']) === 0) {
                return $this->render('/error', ['message' => 'post user not fond']);
            }
            $result['setting'] = (Yii::$app->user->getId() == $user->getId()) ? true : false;

            return $this->render('page', $result);
        }

        return $this->render('/error', ['message' => ' user not fond']);
    }

    /**
     * @return string|Response
     */
    public function actionBookmark()
    {
        if (!Yii::$app->user->isGuest) {
            $result = User::getBookmark(Yii::$app->user->getId(), Yii::$app->params['numberOfPage']);
            if (count($result['posts']) === 0) {
                return $this->render('/error', ['message' => 'bookmark not found']);
            }

            return $this->render('page', $result);
        }

        return $this->redirect('/user/login');
    }

    /**
     * @return string
     */
    public function actionBest() : string
    {
        return $this->render('best', ['users' => User::getBest(10)]);
    }
}

views/post/comment.php
<?php
/* @var $comment \app\models\Comment */

?>

<div class="col-xs-12 alert alert-info ">
    <a href="/user/<?= $comment->user_id ?>"><?= $comment->getUser()->username ?></a><br>
    <?= $comment->content ?>
    <p>
        <?= $comment->created_at ?>
    </p>
    <?php
    if (Yii::$app->user->getId() === $comment->user_id) {
        ?>
        <div data-id="<?= $comment->id ?>">
            <div class="comment remove_comment">
                <i class="fa fa-times" aria-hidden="true"></i>
            </div>
            <div class="comment edit_comment">
                <i class="fa fa-pencil" aria-hidden="true"></i>
            </div>
        </div>
    <?php } ?>
</div>

views/post/create.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \app\models\form\PostForm */

/* @var $categories array of \app\models\Category */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Category;

$this->title = 'Create';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="post-create">
    <div class="row">
        <div class="col-lg-5">
            <?php
            if (Yii::$app->session->hasFlash('success')) {
                echo Yii::$app->session->getFlash('success');
            } elseif (Yii::$app->session->hasFlash('error')) {
                echo Yii::$app->session->getFlash('error');
            }
            $form = ActiveForm::begin(['id' => 'save-form', 'options' => ['enctype' => 'multipart/form-data']]);
            ?>
            <?= $form->field($model, 'category_id')->label('Category')->dropDownList(
                Category::getDropDownList(),
                $params ? $params : ['prompt' => 'выберете катигорию']); ?>

            <?= $form->field($model, 'image')->fileInput(); ?>
            <?php if ($model->image): ?>
                <img src="/image_db/<?= $model->image ?>" alt="">
            <?php endif; ?>
            <?= $form->field($model, 'title')->input('text'); ?>
            <?= $form->field($model, 'content')->textarea(['rows' => '7']); ?>
            <p>Коментарии</p>
            <?= $form->field($model, 'is_comment')->checkbox()->label('вкл/выкл'); ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/post/index.php
<?php

use yii\bootstrap\Nav;
use yii\widgets\LinkPager;
use app\widgets\SiteBarWidget;

/* @var $this yii\web\View */
/* @var $post  app\models\Post */
/* @var $posts  array of Post */
/* @var $pages \yii\data\Pagination */

$this->title = 'My Yii Application';

?>
<div class="site-index">
    <div class="row">
        <?= Nav::widget([
            'items' => [
                ['label' => 'Recent', 'url' => ['post/recent'], 'options' => ['class' => 'col-xs-4']],
                ['label' => 'Popular', 'url' => ['post/popular'], 'options' => ['class' => 'col-xs-4']],
                ['label' => 'Author Best', 'url' => ['user/best'], 'options' => ['class' => 'col-xs-4']]
            ]
        ]); ?>
        <div class="col-12 col-md-9">
            <?php
            foreach ($posts as $post) {
                echo $this->render('template/get', ['post' => $post]);
            }
            ?>
            <?= LinkPager::widget([
                'pagination' => $pages,
            ]); ?>
        </div>
        <div class=" visible-md-block visible-lg-block visible-xl-block col-md-3">
            <?= SiteBarWidget::widget() ?>
        </div>
    </div>
</div>

views/post/page.php
<?php
/* @var $post \app\models\Post */
/* @var $model \app\models\Comment*/
use \app\models\Comment;

use app\assets\CommentAsset;
use yii\widgets\ListView;
use kop\y2sp\ScrollPager;
use \app\models\Post;
CommentAsset::register($this);
echo $this->render('template/get', ['post' => $post, 'textMaxLength' => true]);
?>
<div class="col-xs-12">
    <?php
    if($post->is_comment==Post::COMMENT_ON){
        echo ListView::widget([
            'dataProvider' => $dataProvider,
            'itemOptions' => ['class' => 'item'],
            'itemView' => function (Comment $model, $key, $index, $widget) {
                if($model->status_check==Comment::STATUS_BAN){
                    return '<div class="col-xs-12 alert alert-info ">comment remove</div>';
                }
                return $this->render('comment', ['comment' => $model]);

            },
            'pager' => [
                'class' => ScrollPager::class,
                'enabledExtensions' => [
                    ScrollPager::EXTENSION_TRIGGER,
                    ScrollPager::EXTENSION_SPINNER
                ],
            ],
        ]);
        echo $this->render('/comment/save', ['model' => $model, 'post' => $post]);
    }
    ?>
</div>
<?php